use super::projection::{
    addpoint_source, collect_linked_shapes, contour_bounds, control_source, previous_neighbor,
    previous_point,
};
use anyhow::{Context, Result};
use std::collections::{HashMap, HashSet};
use std::path::Path;
use strok_core::document::Document;
use strok_core::path_point::{CurveMode, PathData};
use strok_core::shape::{Operation, Shape};
use strok_core::types::PointMode;
use strok_core::{dsl_emit, dsl_parse};

#[derive(Clone)]
pub(super) struct FileEdit {
    pub(super) before: Vec<u8>,
    pub(super) after: Vec<u8>,
}

fn point_names(fields: &HashMap<String, String>) -> Result<Vec<&str>> {
    let names: Vec<_> = required(fields, "points")?
        .split(',')
        .map(str::trim)
        .filter(|name| !name.is_empty())
        .collect();
    if names.is_empty() {
        anyhow::bail!("'points' must contain at least one point name");
    }
    let unique: HashSet<_> = names.iter().copied().collect();
    if unique.len() != names.len() {
        anyhow::bail!("'points' contains duplicate point names");
    }
    Ok(names)
}

fn required<'a>(fields: &'a HashMap<String, String>, name: &str) -> Result<&'a str> {
    fields
        .get(name)
        .map(String::as_str)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| anyhow::anyhow!("missing '{}'", name))
}

fn coordinate(fields: &HashMap<String, String>, name: &str) -> Result<f64> {
    let raw = required(fields, name)?;
    let value = raw
        .parse::<f64>()
        .with_context(|| format!("'{}' is not a number", name))?;
    if !value.is_finite() {
        anyhow::bail!("'{}' must be finite", name);
    }
    Ok(value)
}

pub(super) fn apply(file: &Path, fields: &HashMap<String, String>) -> Result<FileEdit> {
    let action = required(fields, "action")?;
    let shape_name = required(fields, "shape")?;
    let original =
        std::fs::read(file).with_context(|| format!("failed to read '{}'", file.display()))?;
    let loaded =
        Document::load(file).with_context(|| format!("failed to load '{}'", file.display()))?;
    let mut scene = loaded
        .scene
        .ok_or_else(|| anyhow::anyhow!("visual editing requires a text .strok document"))?;
    if scene.imported_shape_names.contains(shape_name) {
        anyhow::bail!(
            "'{}' comes from an imported module and cannot be edited here",
            shape_name
        );
    }
    let mut linked_shapes = Vec::new();
    collect_linked_shapes(&scene.nodes, &mut linked_shapes);
    if linked_shapes.iter().any(|name| name == shape_name) {
        anyhow::bail!(
            "'{}' is generated by createlink; edit its source shape instead",
            shape_name
        );
    }

    let coord_space = (scene.document_size.w, scene.document_size.h);
    let shape_index = scene
        .shapes
        .iter()
        .position(|shape| shape.name == shape_name)
        .ok_or_else(|| anyhow::anyhow!("shape '{}' no longer exists", shape_name))?;
    let before = scene.shapes[shape_index].resolve(coord_space);
    let shape = &mut scene.shapes[shape_index];

    match action {
        "move" => {
            let point_name = required(fields, "point")?;
            let x = coordinate(fields, "x")?;
            let y = coordinate(fields, "y")?;
            move_anchor(shape, &before, point_name, (x, y))?;
        }
        "nudge" => {
            let point_name = required(fields, "point")?;
            let dx = coordinate(fields, "dx")?;
            let dy = coordinate(fields, "dy")?;
            let point = before
                .points
                .iter()
                .find(|point| point.name == point_name)
                .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", point_name))?;
            move_anchor(shape, &before, point_name, (point.x + dx, point.y + dy))?;
        }
        "move-anchors" => {
            let point_names = point_names(fields)?;
            let dx = coordinate(fields, "dx")?;
            let dy = coordinate(fields, "dy")?;
            let targets: Vec<_> = point_names
                .iter()
                .map(|name| {
                    let point = before
                        .points
                        .iter()
                        .find(|point| point.name == *name)
                        .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", name))?;
                    Ok((*name, (point.x + dx, point.y + dy)))
                })
                .collect::<Result<_>>()?;
            for (name, target) in targets {
                move_anchor(shape, &before, name, target)?;
            }
        }
        "control" => {
            let point_name = required(fields, "point")?;
            let handle = required(fields, "handle")?;
            let x = coordinate(fields, "x")?;
            let y = coordinate(fields, "y")?;
            move_control(shape, &before, point_name, handle, (x, y))?;
            if let Some(opposite_point) = fields.get("oppositePoint") {
                let opposite_handle = required(fields, "oppositeHandle")?;
                let opposite_x = coordinate(fields, "oppositeX")?;
                let opposite_y = coordinate(fields, "oppositeY")?;
                move_control(
                    shape,
                    &before,
                    opposite_point,
                    opposite_handle,
                    (opposite_x, opposite_y),
                )?;
            }
        }
        "retract-control" => {
            let point_name = required(fields, "point")?;
            let handle = required(fields, "handle")?;
            retract_control(shape, &before, point_name, handle)?;
        }
        "symmetric" => {
            let point_name = required(fields, "point")?;
            symmetrize_anchor(shape, &before, point_name)?;
        }
        "add" => {
            let after = required(fields, "after")?;
            insert_midpoint(shape, &before, after)?;
        }
        "delete" => {
            let point_name = required(fields, "point")?;
            delete_anchor(shape, &before, point_name)?;
        }
        _ => anyhow::bail!("unknown edit action '{}'", action),
    }

    let output = dsl_emit::emit_scene(&scene);
    dsl_parse::parse_file_with_path(&output, file)
        .with_context(|| "edited document failed to parse; the file was not changed")?;
    let after = output.into_bytes();
    std::fs::write(file, &after).with_context(|| format!("failed to save '{}'", file.display()))?;
    Ok(FileEdit {
        before: original,
        after,
    })
}

fn move_anchor(
    shape: &mut Shape,
    data: &PathData,
    point_name: &str,
    target: (f64, f64),
) -> Result<()> {
    let point_index = data
        .points
        .iter()
        .position(|point| point.name == point_name)
        .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", point_name))?;
    let point = &data.points[point_index];
    let delta = (target.0 - point.x, target.1 - point.y);
    let mut moved = false;

    if let Some(index) = shape.operations.iter().rposition(
        |operation| matches!(operation, Operation::AddPoint { name, .. } if name == point_name),
    ) {
        if let Operation::AddPoint { at, .. } = &mut shape.operations[index] {
            at.0 += delta.0;
            at.1 += delta.1;
            moved = true;
        }
    }

    if !moved {
        if let Some(index) = shape.operations.iter().rposition(
            |operation| matches!(operation, Operation::MovePointTo { point, .. } if point == point_name),
        ) {
            if let Operation::MovePointTo { to, .. } = &mut shape.operations[index] {
                to.0 += delta.0;
                to.1 += delta.1;
                moved = true;
            }
        }
    }

    if !moved {
        shape.operations.push(Operation::MovePointTo {
            point: point_name.to_string(),
            to: target,
        });
    }

    // Keep explicit handles attached to the anchor, matching vector-editor
    // expectations. Relative controls follow automatically through their DSL
    // offsets; absolute controls need their stored coordinate nudged too.
    shift_absolute_control(shape, point_name, "c2", delta);
    if let Some(next) = next_point(data, point_index) {
        shift_absolute_control(shape, &next.name, "c1", delta);
    }
    Ok(())
}

pub(super) fn next_point(
    data: &PathData,
    index: usize,
) -> Option<&strok_core::path_point::NamedPoint> {
    let (begin, end) = contour_bounds(data, index)?;
    if index + 1 < end {
        data.points.get(index + 1)
    } else if data.closed {
        data.points.get(begin)
    } else {
        None
    }
}

fn shift_absolute_control(shape: &mut Shape, point: &str, handle: &str, delta: (f64, f64)) {
    let Some(index) = control_source(shape, point) else {
        return;
    };
    if let Operation::AddPoint {
        mode: Some(PointMode::Controls),
        control_c1,
        control_c2,
        ..
    } = &mut shape.operations[index]
    {
        let control = if handle == "c1" {
            control_c1
        } else {
            control_c2
        };
        if let Some(value) = control {
            value.0 += delta.0;
            value.1 += delta.1;
        }
    }
}

fn move_control(
    shape: &mut Shape,
    data: &PathData,
    point_name: &str,
    handle: &str,
    target: (f64, f64),
) -> Result<()> {
    if handle != "c1" && handle != "c2" {
        anyhow::bail!("handle must be 'c1' or 'c2'");
    }
    let point_index = data
        .points
        .iter()
        .position(|point| point.name == point_name)
        .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", point_name))?;
    let point = &data.points[point_index];
    let previous = previous_point(data, point_index)
        .ok_or_else(|| anyhow::anyhow!("point '{}' has no incoming segment", point_name))?;
    let source = control_source(shape, point_name).ok_or_else(|| {
        anyhow::anyhow!(
            "the handles for '{}' are generated by another operation and are read-only",
            point_name
        )
    })?;

    if let Operation::AddPoint {
        mode,
        control_c1,
        control_c2,
        ..
    } = &mut shape.operations[source]
    {
        let value = match mode {
            Some(PointMode::Controls) => target,
            Some(PointMode::ControlsRelative) if handle == "c1" => {
                (target.0 - previous.x, target.1 - previous.y)
            }
            Some(PointMode::ControlsRelative) => (target.0 - point.x, target.1 - point.y),
            _ => anyhow::bail!("point '{}' does not have explicit controls", point_name),
        };
        if handle == "c1" {
            *control_c1 = Some(value);
        } else {
            *control_c2 = Some(value);
        }
    }
    Ok(())
}

fn retract_control(
    shape: &mut Shape,
    data: &PathData,
    point_name: &str,
    handle: &str,
) -> Result<()> {
    let point_index = data
        .points
        .iter()
        .position(|point| point.name == point_name)
        .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", point_name))?;
    let target = match handle {
        "c1" => {
            let previous = previous_neighbor(data, point_index)
                .ok_or_else(|| anyhow::anyhow!("point '{}' has no incoming control", point_name))?;
            (previous.x, previous.y)
        }
        "c2" => {
            let point = &data.points[point_index];
            (point.x, point.y)
        }
        _ => anyhow::bail!("handle must be 'c1' or 'c2'"),
    };
    move_control(shape, data, point_name, handle, target)
}

fn symmetrize_anchor(shape: &mut Shape, data: &PathData, point_name: &str) -> Result<()> {
    let index = data
        .points
        .iter()
        .position(|point| point.name == point_name)
        .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", point_name))?;
    let point = &data.points[index];
    let previous = previous_neighbor(data, index)
        .ok_or_else(|| anyhow::anyhow!("the endpoint '{}' cannot have two controls", point_name))?;
    let next = next_point(data, index)
        .ok_or_else(|| anyhow::anyhow!("the endpoint '{}' cannot have two controls", point_name))?;
    if addpoint_source(shape, &point.name).is_none() || addpoint_source(shape, &next.name).is_none()
    {
        anyhow::bail!(
            "the controls at '{}' are generated and cannot be edited directly",
            point_name
        );
    }

    let dx = next.x - previous.x;
    let dy = next.y - previous.y;
    let length = dx.hypot(dy);
    let direction = if length > 1e-9 {
        (dx / length, dy / length)
    } else {
        (1.0, 0.0)
    };
    let incoming_span = (point.x - previous.x).hypot(point.y - previous.y);
    let outgoing_span = (next.x - point.x).hypot(next.y - point.y);
    let handle_length = (incoming_span.min(outgoing_span) / 3.0).max(1e-3);
    let incoming = (
        point.x - direction.0 * handle_length,
        point.y - direction.1 * handle_length,
    );
    let outgoing = (
        point.x + direction.0 * handle_length,
        point.y + direction.1 * handle_length,
    );

    let incoming_c1 = explicit_controls(data, index)
        .map(|controls| controls.0)
        .unwrap_or((
            previous.x + (point.x - previous.x) / 3.0,
            previous.y + (point.y - previous.y) / 3.0,
        ));
    let outgoing_c2 = data
        .points
        .iter()
        .position(|candidate| candidate.name == next.name)
        .and_then(|next_index| explicit_controls(data, next_index))
        .map(|controls| controls.1)
        .unwrap_or((
            next.x - (next.x - point.x) / 3.0,
            next.y - (next.y - point.y) / 3.0,
        ));

    materialize_controls(shape, &point.name, incoming_c1, incoming)?;
    materialize_controls(shape, &next.name, outgoing, outgoing_c2)?;
    Ok(())
}

fn explicit_controls(data: &PathData, index: usize) -> Option<((f64, f64), (f64, f64))> {
    let point = data.points.get(index)?;
    match point.mode {
        CurveMode::Controls { c1, c2 } => Some((c1, c2)),
        CurveMode::ControlsRelative { c1, c2 } => {
            let previous = previous_point(data, index)?;
            Some((
                (previous.x + c1.0, previous.y + c1.1),
                (point.x + c2.0, point.y + c2.1),
            ))
        }
        CurveMode::Sharp | CurveMode::CatmullRom(_) | CurveMode::Arc { .. } => None,
    }
}

fn materialize_controls(
    shape: &mut Shape,
    point_name: &str,
    c1: (f64, f64),
    c2: (f64, f64),
) -> Result<()> {
    let source = addpoint_source(shape, point_name).ok_or_else(|| {
        anyhow::anyhow!(
            "point '{}' is generated and cannot own controls",
            point_name
        )
    })?;
    let Operation::AddPoint {
        mode,
        tension,
        arc_rx,
        arc_ry,
        arc_sweep,
        arc_large,
        arc_bulge,
        control_c1,
        control_c2,
        ..
    } = &mut shape.operations[source]
    else {
        unreachable!();
    };
    *mode = Some(PointMode::Controls);
    *tension = None;
    *arc_rx = None;
    *arc_ry = None;
    *arc_sweep = None;
    *arc_large = None;
    *arc_bulge = None;
    *control_c1 = Some(c1);
    *control_c2 = Some(c2);
    Ok(())
}

fn insert_midpoint(shape: &mut Shape, data: &PathData, after: &str) -> Result<()> {
    let from_index = data
        .points
        .iter()
        .position(|point| point.name == after)
        .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", after))?;
    let (begin, end) = contour_bounds(data, from_index)
        .ok_or_else(|| anyhow::anyhow!("point '{}' is outside its path", after))?;
    let to_index = if from_index + 1 < end {
        from_index + 1
    } else if data.closed {
        begin
    } else {
        anyhow::bail!("the last point of an open path has no following segment");
    };
    let from = &data.points[from_index];
    let to = &data.points[to_index];
    let mut at = midpoint((from.x, from.y), (to.x, to.y));
    let mut mode = None;
    let mut tension = None;
    let mut control_c1 = None;
    let mut control_c2 = None;

    match to.mode {
        CurveMode::CatmullRom(value) => {
            mode = Some(PointMode::CatmullRom);
            tension = Some(value);
        }
        CurveMode::Controls { c1, c2 } => {
            let (a, d, e, c, point) = split_cubic((from.x, from.y), c1, c2, (to.x, to.y));
            if update_control_source(shape, &to.name, e, c) {
                at = point;
                mode = Some(PointMode::Controls);
                control_c1 = Some(a);
                control_c2 = Some(d);
            }
        }
        CurveMode::ControlsRelative { c1, c2 } => {
            let absolute_c1 = (from.x + c1.0, from.y + c1.1);
            let absolute_c2 = (to.x + c2.0, to.y + c2.1);
            let (a, d, e, c, point) =
                split_cubic((from.x, from.y), absolute_c1, absolute_c2, (to.x, to.y));
            if update_control_source(
                shape,
                &to.name,
                (e.0 - point.0, e.1 - point.1),
                (c.0 - to.x, c.1 - to.y),
            ) {
                at = point;
                mode = Some(PointMode::ControlsRelative);
                control_c1 = Some((a.0 - from.x, a.1 - from.y));
                control_c2 = Some((d.0 - point.0, d.1 - point.1));
            }
        }
        CurveMode::Sharp | CurveMode::Arc { .. } => {}
    }

    let name = unique_point_name(data);
    shape.operations.push(Operation::AddPoint {
        name,
        at,
        after: Some(after.to_string()),
        mode,
        tension,
        arc_rx: None,
        arc_ry: None,
        arc_sweep: None,
        arc_large: None,
        arc_bulge: None,
        control_c1,
        control_c2,
    });
    Ok(())
}

fn update_control_source(shape: &mut Shape, point: &str, c1: (f64, f64), c2: (f64, f64)) -> bool {
    let Some(index) = control_source(shape, point) else {
        return false;
    };
    if let Operation::AddPoint {
        control_c1,
        control_c2,
        ..
    } = &mut shape.operations[index]
    {
        *control_c1 = Some(c1);
        *control_c2 = Some(c2);
        true
    } else {
        false
    }
}

type CubicSplit = ((f64, f64), (f64, f64), (f64, f64), (f64, f64), (f64, f64));

fn split_cubic(p0: (f64, f64), c1: (f64, f64), c2: (f64, f64), p3: (f64, f64)) -> CubicSplit {
    let a = midpoint(p0, c1);
    let b = midpoint(c1, c2);
    let c = midpoint(c2, p3);
    let d = midpoint(a, b);
    let e = midpoint(b, c);
    (a, d, e, c, midpoint(d, e))
}

fn midpoint(a: (f64, f64), b: (f64, f64)) -> (f64, f64) {
    ((a.0 + b.0) / 2.0, (a.1 + b.1) / 2.0)
}

fn unique_point_name(data: &PathData) -> String {
    for index in 1..=usize::MAX {
        let candidate = format!("p{}", index);
        if data.points.iter().all(|point| point.name != candidate) {
            return candidate;
        }
    }
    "point".to_string()
}

fn delete_anchor(shape: &mut Shape, data: &PathData, point_name: &str) -> Result<()> {
    let index = data
        .points
        .iter()
        .position(|point| point.name == point_name)
        .ok_or_else(|| anyhow::anyhow!("point '{}' no longer exists", point_name))?;
    let (begin, end) = contour_bounds(data, index)
        .ok_or_else(|| anyhow::anyhow!("point '{}' is outside its path", point_name))?;
    let minimum = if data.closed { 3 } else { 2 };
    if end - begin <= minimum {
        anyhow::bail!(
            "this {} contour needs at least {} points",
            if data.closed { "closed" } else { "open" },
            minimum
        );
    }
    shape.operations.push(Operation::DeletePoint {
        point: point_name.to_string(),
        reconnect: None,
    });
    Ok(())
}
